version: "3.0"
services:
  prometheus:
    build:
      context: ./prometheus/
      dockerfile: prometheus.dockerfile
    container_name: prometheus
    ports: 
      - 9090:9090
  alertmanager:
    build:
      context: ./alertmanager/
      dockerfile: alertmanager.dockerfile
    container_name: alertmanager
    ports:
      - 9093:9093
  grafana:
    build:
      context: ./grafana/
      dockerfile: grafana.dockerfile
    container_name: grafana
    ports:
      - 3000:3000
  cloudwatch-exporter:
    build:
      context: ./cloudwatch-exporter/
      dockerfile: cloudwatch-exporter.dockerfile
    container_name: cloudwatch-exporter
    ports:
      - 9106:9106