version: "3.0"
services:
  prometheus:
    build:
      context: ./prometheus/
      dockerfile: prometheus.dockerfile
    container_name: prometheus
    ports: 
      - 9090:9090
  alertmanager:
    build:
      context: ./alertmanager/
      dockerfile: alertmanager.dockerfile
    container_name: alertmanager
    ports:
      - 9093:9093
  grafana:
    build:
      context: ./grafana/
      dockerfile: grafana.dockerfile
    container_name: grafana
    ports:
      - 3000:3000
  cloudwatch-exporter:
    build:
      context: ./cloudwatch-exporter/
      dockerfile: cloudwatch-exporter.dockerfile
    container_name: cloudwatch-exporter
    ports:
      - 9106:9106
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100