global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: "monitoring-aws"

rule_files:
  - "alert.rules" 

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets:
          - localhost:9090
  
  - job_name: cloudwatch-exporter
    scrape_interval: 5s
    static_configs:
      - targets:
          - cloudwatch-exporter:9106
  
  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080